name: Automatisation des tests

on: [push]

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Test add
        run: ./build/src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Test sub
        run: ./build/src/calculator sub 10 5

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Test mul
        run: ./build/src/calculator mul 10 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Test div
        run: ./build/src/calculator div 10 5

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div]
    steps:
      - name: Deployment
        run: echo "DÃ©ploiement de la solution"
